# Generated by Django 5.0.2 on 2024-03-02 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('is_allowed', models.BooleanField(default=True)),
                ('signed_at', models.DateTimeField(default=datetime.datetime(2024, 3, 2, 6, 37, 1, 312715, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
